### --------------------------------------------------------
###  Example 1: Initialization macro of nexus.
###  $Id$
### --------------------------------------------------------

/Geometry/RegisterGeometry CYLINDRIC_CHAMBER

/Generator/RegisterGenerator NU_BEAM

/Actions/RegisterRunAction DEFAULT

/Actions/RegisterEventAction DEFAULT

/Actions/RegisterTrackingAction DEFAULT

/control/execute macros/DefaultPhysicsList.mac

/nucd/RegisterMacro macros/nucd_ex1.config.mac
